title: "Dr-Kino - Embedded Systems, RF, Control, Digital Processing, Analog Electronic, Security and Reverse Engineering"
description: > # this means to ignore newlines until "baseurl:"
  Embedded Systems, RF, Control, Digital Processing, Analog Electronic, Security and Reverse Engineering.
destination: ../gh-pages
lsi:         false
port: 4000
markdown: kramdown
permalink:   /:year/:month/:day/:title/
exclude: [design, scripts, README.md]

tag_title_prefix: "Articles Tagged With: "
